
project_id = "mqvstzxrxrmgdseepwzh"

[functions.analyze-resume]
verify_jwt = false
timeout_seconds = 60

[functions.extract-job-content]
verify_jwt = false
timeout_seconds = 60

[functions.search-role-descriptions]
verify_jwt = false
timeout_seconds = 120
